/**
 * Created by Administrator on 2017/1/18.
 */
var data=[];

var dataStr='1、1<br>\
    <br>\
    导演:1<br>\
    编剧:11<br>\
    主演:111<br>\
    类型:1111<br>\
    国家:11111<br>\
    语言;111111<br>\
    上映日期:1111111<br>\
    片场:11111111<br>\
    <br>\
    <br>\
    2、2<br>\
    <br>\
    导演:2<br>\
    编剧:22<br>\
    主演:222<br>\
    类型:2222<br>\
    国家:22222<br>\
    语言;222222<br>\
    上映日期:2222222<br>\
    片场:22222222<br>\
    <br>\
    <br>\
    3、3<br>\
    <br>\
    导演:3<br>\
    编剧:33<br>\
    主演:333<br>\
    类型:3333<br>\
    国家:33333<br>\
    语言;333333<br>\
    上映日期:3333333<br>\
    片场:33333333<br>\
    <br>\
    <br>\
    4、4<br>\
    <br>\
    导演:4<br>\
    编剧:44<br>\
    主演:444<br>\
    类型:4444<br>\
    国家:44444<br>\
    语言;444444<br>\
    上映日期:4444444<br>\
    片场:44444444<br>\
    <br>\
    <br>\
    5、5<br>\
    <br>\
    导演:5<br>\
    编剧:55<br>\
    主演:555<br>\
    类型:5555<br>\
    国家:55555<br>\
    语言;555555<br>\
    上映日期:5555555<br>\
    片场:55555555<br>\
    <br>\
    <br>\
    6、6<br>\
    <br>\
    导演:6<br>\
    编剧:66<br>\
    主演:666<br>\
    类型:6666<br>\
    国家:66666<br>\
    语言;666666<br>\
    上映日期:6666666<br>\
    片场:66666666<br>\
    <br>\
    <br>\
    7、7<br>\
    <br>\
    导演:7<br>\
    编剧:77<br>\
    主演:777<br>\
    类型:7777<br>\
    国家:77777<br>\
    语言;777777<br>\
    上映日期:7777777<br>\
    片场:77777777<br>\
    <br>\
    <br>\
    8、8<br>\
    <br>\
    导演:8<br>\
    编剧:88<br>\
    主演:888<br>\
    类型:8888<br>\
    国家:88888<br>\
    语言;888888<br>\
    上映日期:8888888<br>\
    片场:88888888<br>\
    <br>\
    <br>\
    9、9<br>\
    <br>\
    导演:9<br>\
    编剧:99<br>\
    主演:999<br>\
    类型:9999<br>\
    国家:99999<br>\
    语言;999999<br>\
    上映日期:9999999<br>\
    片场:99999999<br>\
    <br>\
    <br>\
    a、a<br>\
    <br>\
    导演:a<br>\
    编剧:aa<br>\
    主演:aaa<br>\
    类型:aaaa<br>\
    国家:aaaaa<br>\
    语言;aaaaaa<br>\
    上映日期:aaaaaaa<br>\
    片场:aaaaaaaa<br>\
    <br>\
    <br>\
    b、b<br>\
    <br>\
    导演:b<br>\
    编剧:bb<br>\
    主演:bbb<br>\
    类型:bbbb<br>\
    国家:bbbbb<br>\
    语言;bbbbbb<br>\
    上映日期:bbbbbbb<br>\
    片场:bbbbbbbb<br>\
    <br>\
    <br>\
    c、c<br>\
    <br>\
    导演:c<br>\
    编剧:cc<br>\
    主演:ccc<br>\
    类型:cccc<br>\
    国家:ccccc<br>\
    语言;cccccc<br>\
    上映日期:ccccccc<br>\
    片场:cccccccc<br>\
    <br>\
    <br>\
    d、d<br>\
    <br>\
    导演:d<br>\
    编剧:dd<br>\
    主演:ddd<br>\
    类型:dddd<br>\
    国家:ddddd<br>\
    语言;dddddd<br>\
    上映日期:ddddddd<br>\
    片场:dddddddd<br>\
    <br>\
    <br>\
    e、e<br>\
    <br>\
    导演:e<br>\
    编剧:ee<br>\
    主演:eee<br>\
    类型:eeee<br>\
    国家:eeeee<br>\
    语言;eeeeee<br>\
    上映日期:eeeeeee<br>\
    片场:eeeeeeee<br>\
    <br>\
    <br>\
    f、f<br>\
    <br>\
    导演:f<br>\
    编剧:ff<br>\
    主演:fff<br>\
    类型:ffff<br>\
    国家:fffff<br>\
    语言;ffffff<br>\
    上映日期:fffffff<br>\
    片场:ffffffff<br>\
    <br>\
    <br>\
    g、g<br>\
    <br>\
    导演:g<br>\
    编剧:gg<br>\
    主演:ggg<br>\
    类型:gggg<br>\
    国家:ggggg<br>\
    语言;gggggg<br>\
    上映日期:ggggggg<br>\
    片场:gggggggg<br>\
    <br>\
    <br>\
    h、h<br>\
    <br>\
    导演:h<br>\
    编剧:hh<br>\
    主演:hhh<br>\
    类型:hhhh<br>\
    国家:hhhhh<br>\
    语言;hhhhhh<br>\
    上映日期:hhhhhhh<br>\
    片场:hhhhhhhh<br>\
    <br>\
    <br>\
    i、i<br>\
    <br>\
    导演:i<br>\
    编剧:ii<br>\
    主演:iii<br>\
    类型:iiii<br>\
    国家:iiiii<br>\
    语言;iiiiii<br>\
    上映日期:iiiiiii<br>\
    片场:iiiiiiii<br>\
    <br>\
    <br>\
    j、j<br>\
    <br>\
    导演:j<br>\
    编剧:jj<br>\
    主演:jjj<br>\
    类型:jjjj<br>\
    国家:jjjjj<br>\
    语言;jjjjjj<br>\
    上映日期:jjjjjjj<br>\
    片场:jjjjjjjj<br>\
    <br>\
    <br>\
    k、k<br>\
    <br>\
    导演:k<br>\
    编剧:kk<br>\
    主演:kkk<br>\
    类型:kkkk<br>\
    国家:kkkkk<br>\
    语言;kkkkkk<br>\
    上映日期:kkkkkkk<br>\
    片场:kkkkkkkk<br>\
    ';

var d=dataStr.split('<br>    <br>    <br>    ');
for (var i=0;i<d.length;i++){
    var c=d[i].split('<br>    <br>    ');
    data.push({
        img: c[0].replace('、',' ')+'.jpg',
        caption: c[0].split('、')[1],
        desc: c[1]
    });
}

